language: go
go:
 - "1.x"

os: osx

install: true

addons:
  homebrew:
    packages:
    - lame
    update: true

env:
  global:
    - CODECOV_TOKEN="6b436247-e56d-41ec-ad0b-bfb3c70caac9"

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)