// Code generated by "stringer -type=ChannelMode,BitRateMode -output=stringers.go"; DO NOT EDIT.

package mp3

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mono-0]
	_ = x[Stereo-1]
	_ = x[JointStereo-2]
}

const _ChannelMode_name = "MonoStereoJointStereo"

var _ChannelMode_index = [...]uint8{0, 4, 10, 21}

func (i ChannelMode) String() string {
	if i < 0 || i >= ChannelMode(len(_ChannelMode_index)-1) {
		return "ChannelMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelMode_name[_ChannelMode_index[i]:_ChannelMode_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CBR-0]
	_ = x[ABR-1]
	_ = x[VBR-2]
}

const _BitRateMode_name = "CBRABRVBR"

var _BitRateMode_index = [...]uint8{0, 3, 6, 9}

func (i BitRateMode) String() string {
	if i < 0 || i >= BitRateMode(len(_BitRateMode_index)-1) {
		return "BitRateMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BitRateMode_name[_BitRateMode_index[i]:_BitRateMode_index[i+1]]
}
