name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Insall go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name:  Install lame
      run:   |
            if [ '$RUNNER_OS' == 'Windows' ]; then
                  choco install lame
            elif [ '$RUNNER_OS' == 'macOS' ]; then
                  brew install lame
            fi
      shell: bash
    - name: Test
      run: go test --race --coverprofile=coverage.txt --covermode=atomic ./...
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt