name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Insall go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name:  Install lame macOS
      if: runner.os == 'macOS'
      run: brew install lame
    - name:  Install lame Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y lame
    - name: Test
      run: |
        LDFLAGS=-L/usr/local/lib go test --race --coverprofile=coverage.txt --covermode=atomic ./...
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt